root: true

extends:
  - eslint:recommended
  - plugin:svelte/recommended
  - raven

rules:
  no-inner-declarations: 0
  no-undefined: 0
  no-console: 0
  no-magic-numbers: 0
  no-extra-parens: 0
  sort-keys: 0
  sort-vars: 0
  complexity: 0
  max-len: 0
  linebreak-style: 0
  space-before-function-paren: 0
  newline-per-chained-call: 0
  id-length: [warn, { exceptions: [i, j, k, x, y] }]
  multiline-comment-style: [error, separate-lines]
  svelte/indent: [error, { indent: tab, switchCase: 0 }]

overrides:
  - files:
      - "*.svelte"
    parser: svelte-eslint-parser

parserOptions:
  sourceType: module
  ecmaVersion: 2020
  extraFileExtensions: [.svelte]

env:
  browser: true
  es2020: true
  node: true
