name: Build/release

on: 
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: ['3.10']

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Configuring yarn and pip
        run: |
          python -m pip install --upgrade pip
          yarn install

      - name: Building desktop app
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            yarn build-electron-linux
          elif [ "$RUNNER_OS" == "Windows" ]; then
            yarn build-electron-windows
          else
            yarn build-electron-mac